dev

diff --git a/.github/workflows/local_wheel.yml b/.github/workflows/local_wheel.yml
--- a/.github/workflows/local_wheel.yml
+++ b/.github/workflows/local_wheel.yml
@@ -4,6 +4,41 @@ on:
   push:
 
 jobs:
+  run_test_macos_10_15:
+    name: Check that MacOS 10.15 package can be installed from local pip
+    runs-on: macos-10.15
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install reqs
+        run: |
+          g++ test.cpp -o test && ./test
+          sysctl -a | grep machdep
+          pip3 install -r requirements.txt
+          brew install libomp
+      - name: Build local wheel
+        run: |
+          gcc -fopenmp -march=knl -mavx512f -dM -E - < /dev/null | egrep "SSE|AVX" | sort
+          pip3 install wheel
+          python3 setup.py sdist bdist_wheel
+          ls -lah dist/
+          brew uninstall libomp
+      - name: Install QSim
+        run: |
+          pip3 install dist/qsimcirq-0.10.0.dev20210623-cp38-cp38-linux_x86_64.whl
+          brew install libomp
+      - name: Run tests
+        run: |
+          rm -rf qsimcirq/
+          pytest qsimcirq_tests/qsimcirq_test.py || echo "failure!"
+          cat ./example.txt
+#          ls -lah . && cat o.txt
+      - name: Upload wheel binary to PyPI
+        env:
+          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
+          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
+        run: |
+          twine upload --skip-existing ./dist/*.whl
   run_test_ubuntu_20_04:
     name: Check that Ubuntu 20.04 package can be installed from local pip
     runs-on: ubuntu-20.04
@@ -12,9 +47,12 @@ jobs:
       - name: Install reqs
         run: |
           gcc -fopenmp -march=native -dM -E - < /dev/null | egrep "SSE|AVX" | sort
+          g++ test.cpp -o test && ./test
+          pip3 install -r requirements.txt
       - name: Build local wheel
         run: |
           cat /proc/cpuinfo
+          sudo apt-get install -y gdb
           pip3 install wheel
           python3 setup.py sdist bdist_wheel
           cat ./build_log ||  echo "$$$ no build log!"
@@ -46,3 +84,76 @@ jobs:
 #        run: |
 #          auditwheel repair dist/qsimcirqq-0.10.0.dev20210623-cp38-cp38-linux_x86_64.whl
 #          twine upload --skip-existing ./wheelhouse/*.whl
+  run_test_ubuntu_18_04:
+    name: Check that Ubuntu 18.04 package can be installed from local pip
+    runs-on: ubuntu-18.04
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install reqs
+        run: |
+          g++ test.cpp -o test && ./test
+          gcc -fopenmp -march=knl -mavx512f -dM -E - < /dev/null | egrep "SSE|AVX" | sort
+          cat /proc/cpuinfo
+          sudo apt-get install -y python3-setuptools gdb
+          pip3 install --upgrade pip
+          pip3 install -r requirements.txt
+      - name: Build local wheel
+        run: |
+          pip3 install wheel
+          python3 setup.py sdist bdist_wheel
+      - name: Install QSim
+        run: |
+          pip3 install dist/qsimcirq-0.9.5-cp36-cp36m-linux_x86_64.whl
+      - name: Run tests
+        run: |
+          rm -rf qsimcirq/
+          pytest qsimcirq_tests/qsimcirq_test.py || echo "failure!"
+          find . -name 'example.txt'
+          cat ./example.txt
+#          ls -lah . && cat o.txt
+  run_test_win:
+    name: Check that Windows Server 2019 package can be installed from local pip
+    runs-on: windows-2019
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install reqs
+        run: |
+          g++ test.cpp -o test && ./test
+          Get-CimInstance CIM_Processor
+          pip3 install -r requirements.txt
+      - name: Build local wheel
+        run: |
+          pip3 install wheel
+          python3 setup.py sdist bdist_wheel
+      - name: Install QSim
+        run: |
+          pip3 install dist/qsimcirq-0.9.5-cp37-cp37m-win_amd64.whl
+      - name: Run tests
+        run: |
+          rm -R qsimcirq/
+          pytest --pdb qsimcirq_tests/qsimcirq_test.py
+          dir
+          type example.txt
+  run_test_win_2016:
+    name: Check that Windows Server 2016 package can be installed from local pip
+    runs-on: windows-2016
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install reqs
+        run: |
+          g++ test.cpp -o test && ./test
+          Get-WmiObject Win32_Processor
+          pip3 install -r requirements.txt
+      - name: Build local wheels
+        run: |
+          pip3 install wheel
+          python3 setup.py sdist bdist_wheel
+      - name: Install QSim
+        run: |
+          pip3 install dist/qsimcirq-0.9.5-cp37-cp37m-win_amd64.whl
+      - name: Run tests
+        run: |
+          rm -R qsimcirq/
+          pytest --pdb qsimcirq_tests/qsimcirq_test.py
+          dir
+          type example.txt
